#!/bin/bash

###############################################################################
# SCRIPT NAME: recover_branches_from_log.sh
#
# PURPOSE:
#   Recreate LOCAL Git branches from the CSV log generated by the deletion
#   script (git_report/deleted_branches_log.csv).
#
#   Each log entry should contain:
#     - branch_name
#     - full_commit_id
#     - deletion_time_iso
#
# BEHAVIOR:
#   - By default, attempts to restore ALL branches in the log file.
#   - If a branch name is passed as an argument, restores ONLY that branch.
#   - Skips branches that already exist locally.
#   - Skips log entries whose commit ID is not found in the repo.
#
# USAGE:
#   Restore ALL logged branches:
#       ./recover_branches_from_log.sh
#
#   Restore a SINGLE branch:
#       ./recover_branches_from_log.sh feature-1
#
# REQUIREMENTS:
#   - Run inside the Git repository where branches should be restored.
#   - Log file must exist at: git_report/deleted_branches_log.csv
#
###############################################################################

LOG_FILE="git_reports/deleted_branches_log.csv"

# Optional: branch name to recover (if provided)
TARGET_BRANCH="$1"

if [[ ! -f "$LOG_FILE" ]]; then
    echo "❌ Log file not found: $LOG_FILE"
    exit 1
fi

echo "===== BRANCH RECOVERY STARTED ====="
echo "Using log file: $LOG_FILE"

if [[ -n "$TARGET_BRANCH" ]]; then
    echo "Restoring ONLY branch: $TARGET_BRANCH"
else
    echo "Restoring ALL branches from log."
fi

# Skip header and read each log line
tail -n +2 "$LOG_FILE" | while IFS=',' read -r branch_name full_commit_id deletion_time
do
    # Clean potential CRLF artifacts
    branch_name="${branch_name%$'\r'}"
    full_commit_id="${full_commit_id%$'\r'}"

    # If a specific branch is requested, skip others
    if [[ -n "$TARGET_BRANCH" && "$branch_name" != "$TARGET_BRANCH" ]]; then
        continue
    fi

    if [[ -z "$branch_name" || -z "$full_commit_id" ]]; then
        echo "⚠️  Skipping malformed log entry (missing branch or commit):"
        echo "    branch_name='$branch_name', full_commit_id='$full_commit_id'"
        continue
    fi

    # Check if branch already exists locally
    if git show-ref --verify --quiet "refs/heads/$branch_name"; then
        echo "⏭️  Branch already exists, skipping: $branch_name"
        continue
    fi

    # Check if commit exists in this repo
    if ! git cat-file -e "${full_commit_id}^{commit}" 2>/dev/null; then
        echo "❌ Commit not found for branch '$branch_name', skipping."
        echo "   Commit ID: $full_commit_id"
        continue
    fi

    # Create the branch from the commit
    echo "✅ Restoring branch '$branch_name' at commit $full_commit_id"
    git branch "$branch_name" "$full_commit_id"

done

echo "===== BRANCH RECOVERY COMPLETE ====="